### ISSUE TITLE
HtmlToPdfConverter Error

### ISSUE THREAD

**Issue by rgilsimoes** [volkanceylan/Serenity#1436]
Hi,
I'm having this error on a Report:
[InvalidOperationException: PDF generator returned error code -1073740791!]

Line 130:            return converter.Execute();

I get this error because of this code:

```
<div class="row">
            @{var numItems = 1;}
            <div class="col-sm-3">
                <ul>
                    @{
                        foreach (var d in Model.MyItems)
                        {
                            //var novaColuna = "";
                            <li>@d.IdMyItem</li>
                            if (numItems % 15 == 0)
                            {
                                @:</ul></div><div class="col-sm-3"><ul>
                            }
                            numItems = numItems + 1;
                        }
                    }
                </ul>
            </div>
            Total @numItems ;
        </div>
```

But only happens when I have less than 10 elements on my foreach loop. If it reaches 10 it crashes.

**Comment by volkanceylan** [comment]
Your html is probably malformed.

**Comment by volkanceylan** [comment]
To see your report in HTML mode, do

```
            buttons.push(Serene.Common.ReportHelper.createToolButton({
                title: 'Invoice',
                cssClass: 'export-pdf-button',
                reportKey: 'Northwind.OrderDetail',
                extension: 'html',
                getParams: () => ({ OrderID: this.get_entityId() })
            }));
```
e.g. add extension: 'html', check that you have no errors in browser console, check html etc.

**Comment by rgilsimoes** [comment]
The problem was with wkhtmltopdf version. I was using 32 bit instead of 64.

**Comment by jmace** [comment]
@rgilsimoes , I have this issue as well once I have published my application to a test server. I do not have this issue while running it from visual studio. Do you suggest going to http://wkhtmltopdf.org/downloads.html and downloading/installing the 64 bit version as a solution?

**Comment by jmace** [comment]
Can confirm the above solution. Published to a windows server 2008 R2 (64 bit), had to swap out the wkhtmltopdf exe for the 64 bit version. 

Also tried installing the Visual C++ packages for both 32 and 64 bit on the server, but that did not fix my issue.

**Comment by korlu** [comment]
I am having same issue. I tried the 64 bit, but it did NOT fix the problem.

**Comment by Judhianto** [comment]
I am having same issue.

I don't have problem when tested from Visual Studio.

My project is published as docker container run in linux server, everything ok except pdf report involved wkhtmltopdf . 
I tried to install wkhtmltopdf in the container and copy wkhtmltopdf file into folder where the application dll located, but still not working.

I am using serenity 5.0.43

can somebody help me?
