### ISSUE TITLE
Sergen Code Generatorfor Oracle DB

### ISSUE THREAD

**Issue by vigneshkumar957** [volkanceylan/Serenity#4155]
Hi,

I am trying to generate code for my oracle DB but i ma getting following error. i have give following information for adding new connection.

Connection Key : Sample
Connection String : Data Source=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=xxx.com)(PORT=1521)) (CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=aaaa)));User Id=xxxx;Password=yyy
providerName : Oracle.ManagedDataAccess.Client

**Error**

> System.NullReferenceException: Object reference not set to an instance of an object. at Serenity.CodeGenerator.RowGenerator.ClassNameFromTableName(String tableName) at Serenity.CodeGenerator.MainWindow.ConnectionsCombo_SelectionChanged(Ob ject sender, SelectionChangedEventArgs e)

**Comment by kilroyFR** [comment]
See code in my pullrequest : https://github.com/volkanceylan/Serenity/pull/3309

i have fixed this

**Comment by vigneshkumar957** [comment]
Can you please elaborate.. I have same config in my environment as you suggested but still getting the same error.

**Comment by vigneshkumar957** [comment]
@kilroyFR @volkanceylan  Hi, Oracle table is coming after modified with your code but it is not pulling the Oracle view. Can you please assist?

**Comment by kilroyFR** [comment]
hey Volkan,

I was wondering if such a design could be valid for serenity ?
It's an extract from a prototype of an application being redesigned at my office. I have more screenshot i can share if that can help improve or add serenity some nice design patterns.

The 'EDIT FILTER' button we generally find at the bottom/right of SlickGrid is moved up to top of the grid and replaced by a 'FILTER' icon.
All buttons are FLAT (as modern re-design seems to follow this trends).

Cheers
