### ISSUE TITLE
Setting title of EqualityFilter is not working.

### ISSUE THREAD

**Issue by ramveersgh** [volkanceylan/Serenity#549]
Here is my code to set title of filter -  
`AddEqualityFilter<LookupEditor>(Fields.VoucherType, title: "Voucher Type",
                options: new LookupEditorOptions { LookupKey = VoucherTypeRow.LookupKey, MinimumResultsForSearch = 10 });`

But this is not working and still it is showing the filed display name set in row.cs.

**Comment by volkanceylan** [comment]
That option only works for fields that doesn't match an actual field in database. You may do workaround for now using "voucherType" as field name instead of "VoucherType".

**Comment by ramveersgh** [comment]
ok, Thanks.
I used Fields.VoucherType.ToLower() as workaround and its working.
But this is not working with
` AddDateRangeFilter(Fields.VoucherDate.ToLowerCase(), "Voucher Period");`

Display name of Fields.VoucherDate is "Date" and I want to so it as "Voucher Period". After adding ToLower its display title as 'voucherdate'

**Comment by volkanceylan** [comment]
Do it with jQuery than

**Comment by volkanceylan** [comment]
This should be resolved in 2.0.5

**Comment by ramveersgh** [comment]
Still seems not fixed. 
Using `AddDateRangeFilter("voucherDate", "Voucher Period");` is displaying voucherDate instead of Voucher Period.

**Comment by wldkrd1** [comment]
I think this is affecting all the filter types; it's no longer grabbing the NameField by default, it's grabbing the IDField.

**Comment by volkanceylan** [comment]
What do you mean by grabbing ID field? For title?

**Comment by volkanceylan** [comment]
Oh saw it grab me a coffee

**Comment by volkanceylan** [comment]
It was due to a TypeScript change. Should be resolved with 2.0.6.

**Comment by wldkrd1** [comment]
Confirmed resolved with 2.0.6, thanks!

**Comment by ramveersgh** [comment]
Yes, This fixed in 2.0.6. Thanks!
